app = "email-management-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["python-buildpack"]

[env]
PORT = "8000"

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script_checks = []

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
type = "http"
path = "/"