[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --timeout 120 --max-requests 1000 --max-requests-jitter 50"

[services]
[services.api]
name = "email-management-api"
port = 8000
healthcheck = "/"

[services.api.environment]
PORT = "8000"
HOST = "0.0.0.0"